# Railway Configuration
# This file configures how Railway deploys your WhatsApp handler application

[build]
# Use Nixpacks for automatic build detection
builder = "NIXPACKS"

[deploy]
# Start command - Railway will automatically detect Bun and use it
startCommand = "bun run src/index.ts"

# Health check for monitoring
healthcheckPath = "/"

# Restart policy for reliability
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10
